### ISSUE TITLE
Java classes do not support comments before the root element

### ISSUE THREAD

**Issue by tofi86** [schxslt/schxslt#76] opened 2019-09-04 12:28 UTC
Hi,

I'm using the maven 1.2.1 implementation of schxslt which workes very well in general. We only stumbled upon an issue when using XML comments before the root element:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright stuff -->

<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2">

	[...]
```

With the following java/groovy code in gradle

```groovy
[...]
def schematron = new Schematron(xsdSchematron);
def schResult = schematron.validate(xml);
if(schResult.isValid()) {
	println ".... OK"
} else {
	schResult.getValidationMessages().each {
		println it
	}
	println ".... FAILED"
	throw new GradleException("Schematron validation FAILED for '${xml.name}'")
}
[...]
```

the sample above results in the following error:

```
com.sun.org.apache.xerces.internal.dom.DeferredCommentImpl cannot be cast to org.w3c.dom.Element
```

The Gradle/Groovy implementation works well in other cases. If we remove the comment or move it as a child in the root element everything works well again.

Can you have a look at this? Thanks!

Best,
Tobias

**Comment by dmj** [comment] 2019-09-05 18:31
This seems to be a duplicate of https://github.com/schxslt/schxslt/issues/63 and will be fixed in an upcoming release. Thanks for reporting!

**Closed by dmj** 2019-09-05 18:31 UTC
Labels: bug, duplicate

**Comment by tofi86** [comment] 2019-09-05 21:02
Ah, thanks! I didn't scan the closed issues, sorry.
Looking forward to v1.3
