### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by djbpitt** [schxslt/schxslt#96] opened 2020-03-03 19:39 UTC
Clone, pull, cd, `make` errors out at:

```
basex -c "TEST src/test/xquery/basex/"
<testsuites time="PT0.707S">
  <testsuite name="file:///Users/djb/repos/schxslt/src/test/xquery/basex/test.xqm" time="PT0.659S" tests="4" failures="0" errors="3" skipped="0">
    <testcase name="fail-on-unsupported-query-binding" time="PT0.025S"/>
    <testcase name="validate-with-param" time="PT0.307S">
      <error line="92" column="89" uri="file:///Users/djb/repos/schxslt/src/main/xquery/basex/content/schxslt.xqm" type="xslt:error">
        <info/>
      </error>
    </testcase>
    <testcase name="validate-with-xslt" time="PT0.059S">
      <error line="92" column="89" uri="file:///Users/djb/repos/schxslt/src/main/xquery/basex/content/schxslt.xqm" type="xslt:error">
        <info/>
      </error>
    </testcase>
    <testcase name="validate-with-xslt2" time="PT0.01S">
      <error line="92" column="34" uri="file:///Users/djb/repos/schxslt/src/main/xquery/basex/content/schxslt.xqm" type="xslt:error">
        <info>ERROR:  'file:///Users/djb/repos/schxslt/src/main/xquery/basex/content/xslt/2.0/include.xsl: line 46: An attribute whose value must be a QName or whitespace-separated list of QNames had the value '#current''
FATAL ERROR:  'file:///Users/djb/repos/schxslt/src/main/xquery/basex/content/xslt/2.0/include.xsl: line 70: Required attribute 'select' is missing.'</info>
      </error>
    </testcase>
  </testsuite>
</testsuites>
Result: 4 tests, 0 failures, 3 errors, 0 skipped.
make: *** [Makefile:6: test] Error 1
```

**Comment by dmj** [comment] 2020-03-03 19:59
Thanks for reporting! Which version of BaseX are you using?

**Comment by djbpitt** [comment] 2020-03-03 22:25
@dmj 9.3.1. But ... er ... did I need to edit the Makefile to tell it where to find my installation of BaseX?

**Comment by dmj** [comment] 2020-03-04 06:48
@djbpitt No. The Makefile picks up BaseX from your path. I can reproduce the problem: You BaseX only supports XSLT 1.0 with the Xalan processor. 

The first two error messages indicate some problem with passing a parameter to the validation stylesheet when using Xalan (https://github.com/schxslt/schxslt/issues/97).

The third error occurs because the test for the queryBinding xslt2 is run even if you BaseX lacks the support for XSLT 2.0 (https://github.com/schxslt/schxslt/issues/98).

**Comment by djbpitt** [comment] 2020-03-04 14:32
@dmj Aha! Had I read the BaseX installation instructions (sigh) and added Saxon 9 to my CLASSPATH, I wouldn’t have been using Xalan and XSLT 1.0 in the first place. When I do that, the build runs to completion.

**Comment by dmj** [comment] 2020-03-04 18:43
@djbpitt Perfect! Btw: All the build does is to run the tests. I'll close this issue and address the problems w/ Xalan in #97 and #98 respectively, if this is okay with you.

**Comment by djbpitt** [comment] 2020-03-04 19:09
@dmj Okay with me. Thank you, David!

**Closed** 2020-03-05 06:54 UTC
